### ISSUE TITLE
Keyboard not work - android TV 9  @ STB MECOOL K5

### ISSUE THREAD

**Issue by kszwaba** [bk138/droidVNC-NG#87] opened 2022-06-04 20:14 UTC
Hello 

My keyboard RT7D60 not work.
Only ESC key work, others keys not.
I use droidVNG-ng v.1.3 and Reminna VNC client in Linux Mint 17.3 32-bit
DroidVNC-NG is installed on TV Android 9 in MECOOL K5 STB
I have installed "No keyboard" app bit this not help
Sorry fo my English.
Christopher 

![Screenshot at 2022-06-04 21:42:30](https://user-images.githubusercontent.com/80651892/172023929-c1f7b743-4d7b-414b-922c-1b486cb932bb.png)

**Comment by bk138** [comment] 2022-06-05 12:55
Dupe of #4. Please take the time to look for existing issues before reporting a new one :-)

**Closed by bk138** 2022-06-05 12:55 UTC
Labels: bug
