### ISSUE TITLE
Specular screen of chromebook

### ISSUE THREAD

**Issue by DavRas89** [bk138/droidVNC-NG#175] opened 2023-10-24 17:03 UTC
**Is your feature request related to a problem? Please describe.**
Hello! Your app is the only one i was able to install on a chromebook to connect to a vnc viewer on PC and smartphone. The problem is that on vnc viewers the screen of the chromebook appears vertically specular/reflected. Is there a way to solve it?
![Screenshot_20231024_185555_bVNC Free](https://github.com/bk138/droidVNC-NG/assets/148895455/9201b6e1-aac2-476f-8342-6d985d12c173)
![Screenshot_20231024_184815_bVNC Free](https://github.com/bk138/droidVNC-NG/assets/148895455/71e63799-d3c1-4520-94f3-4e078680b072)

**Describe the solution you'd like**
Maybe adding a settings to regulate the specular view/rotation of the shared screen.

**Your environment (please complete the following information):**
 - droidVNC-NG version: latest on playstore
 - Android version: chromebook android
- vnc viewers: real vnc and other apps on playstore 

Thank you!

**Comment by bk138** [comment] 2023-10-25 06:54
We can add ChromeOS-specific logic, but I wonder if other ChromeOS users (@CoolGames from #81, @Dingo88 from #156) see this as well or it is just specific to your device?

**Comment by Dingo88** [comment] 2023-10-25 08:13
No I don't get that result, I get what looks like a mirror reflecting another mirror regardless of what device I connect to. I've been pulling my hair out where the issue is

**Comment by bk138** [comment] 2023-10-25 08:20
@DavRas89 can you pls try with https://gitlab.com/vijai/screenrecorder to see what orientation the recorded video has?

**Comment by DavRas89** [comment] 2023-10-25 09:57
@bk138 thank you very much for your kindness and for the fast answer! Sure, i will try to use screenrecorderi n the afternoon. Is it for windows? In the meantime, here is a picture of the two computers (on the left chrome server and on the right windows with viewer) together:
![IMG-20231024-WA0003](https://github.com/bk138/droidVNC-NG/assets/148895455/72a693dd-579e-493b-9278-66e74d4294fd)

**Comment by bk138** [comment] 2023-10-25 10:00
@DavRas89 It's for Android, i.e. please try it on the ChromeOS machine where you have droidVNC-NG running and check if the recorded video is upside down as well (screenrecorder uses the same API for screen capturing as droidVNC-NG does).

**Comment by DavRas89** [comment] 2023-10-25 14:25
@bk138 i'm trying to install the app screenrecorder but it is not on google playstore (it says that there is a problem and doesn't open the page). I managed to download the apk, but the chromebook is from school (i am a teacher, i have access to google admin console so i can activate apps on playstore if they are on it) and so i'm having some difficulties...is there another app suitable that i can find on playstore? Thank you!

**Comment by DavRas89** [comment] 2023-10-25 14:54
Ok, thank you!
I managed to install another screen recorder, it opened the same authorization to share the screen. And, same results, with the video file mirrored.

https://github.com/bk138/droidVNC-NG/assets/148895455/42a145ad-8255-4f00-802b-b0499c9a9316

Thank you for the other app, i'm testing it, anyway yours is better because the other one has autostart only as payed function.

**Comment by bk138** [comment] 2023-10-25 19:59
@DavRas89 We need the 'model' string of your device, you can get it for instance via https://play.google.com/store/apps/details?id=com.ytheekshana.deviceinfo second tab.

**Comment by DavRas89** [comment] 2023-10-25 21:45
@bk138 here is a picture of the information you asked, it shows model: grunt
![20231025_234321](https://github.com/bk138/droidVNC-NG/assets/148895455/82a57fd3-2ab9-4b52-a3bc-1f62a4025f95)

**Comment by bk138** [comment] 2023-11-06 14:11
@DavRas89 can you try this apk and see if it fixes things for you? ->
[app-release.zip](https://github.com/bk138/droidVNC-NG/files/13267601/app-release.zip)

**Comment by DavRas89** [comment] 2023-11-06 15:07
@bk138 thank you very much! I'm trying but unfortunately i can't activate ADB debugging because it seems locked on organization device, even if i try to unlock from google admin console. I'm not so confident on using developer mode on these school chromebooks. I will keep on trying to find a way...

**Comment by bk138** [comment] 2023-11-25 10:17
@DavRas89 are you able to join the alpha or beta track at google play?

**Comment by bk138** [comment] 2023-12-01 13:14
Tentatively closing this for now, please post here once you got new info @DavRas89.

**Closed by bk138** 2023-12-01 13:14 UTC
Labels: bug, answer-needed
