### ISSUE TITLE
no input on Raspberry PI CM4 running Android 13

### ISSUE THREAD

**Issue by EagleDTW** [bk138/droidVNC-NG#108] opened 2022-10-11 00:04 UTC
**Describe the bug**
I've used this vnc viewer on an Rpi4 omnirom on android 11 and this was the best solution, really great integration of vnc settings to still allow screen timeout after the viewer connection had closed (this is a unique feature of droidVNC and makes it a great app!). With the new omnirom android 13 on a cm4 (Raspberry pi compute module 4) the system connects perfectly and sends all screen images (although permission to cast comes up at boot every time, would be nice to set and forget) but no button presses or screen inputs are recorded - I looked through all permissions (they're all granted) and settings (in developer tab) and found nothing that seems attributable to getting input recognized on the screen.

**To Reproduce**
1. Hook up a Rpi cm4 to a nano waveshare board, this has usb and hdmi connections hooked up to a mini waveshare screen
2. Flashed with omnirom recovery image then installed android 13 rom image.
3. Gave fixed ip address and installed droid vnc.
4. Started the app and granted all permisions - no input from remote vnc viewer.
5. Uninstalled droid vnc and re-installed and ensured all permissions granted and all 3 of them called out in app say granted (including input). 

**Expected Behavior**
I expected that the VNC would connect to server and input button or key presses would come through and be displayed/used.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.3.4
 - Android version: 13
 - Client-side OS and version: iOS 16.0.2 MacOS 10.13.6
 - VNC client and version: RealVNC 3.9.4.46006/6.21.406 & screen sharing built in function on MacOS as well

**Additional context**
I know that this is a fringe case of a device that has experimental OS on it as well, so multiple angles of complication in where the issue is really attributed to, but would love some help to get operational on this implementation as this is installed as a wall tablet in my infrastructure and this is the last piece to come together and make it seamless for the re-install since pulling out the Rpi4 and installing the Rpi cm4 and upgrading to android 13 - any help is very much appreciated!

**Comment by bk138** [comment] 2022-10-11 06:48
>

**Comment by bk138** [comment] 2022-10-11 06:54
> (although permission to cast comes up at boot every time, would be nice to set and forget)

For this, please see https://github.com/bk138/droidVNC-NG/blob/master/README.md#notes

> but no button presses or screen inputs are recorded - I looked through all permissions (they're all granted) and settings (in developer tab) and found nothing that seems attributable to getting input recognized on the screen.

Keyboard input is still in the works (#4), pointer input should work though. If it does not, it very probably is something on the host OS side, akin to #11. Not much we can do here unless you find another API for injecting input on this OS :-/ Have you tried alphavnc?

**Comment by EagleDTW** [comment] 2022-10-11 19:02
I see adb method for permissions - will also try the additional permissions command to see if that allows input to be fully granted.

pointer input was moving around screen - using Mac mouse did not get click action - will need to see if ctrl click has any effect as there is only left click functionality (which may be enough for correct interaction [that I wasn't seeing on screen])

Key and pointer clicks were both not working on droid vnc and alpha vnc, there is an rom image built in vnc that works correctly - but I don't know what differences have been implemented to get this functionality.

Although I do agree that this is a similar port issue like lineageOS, this is a different rom...I think that if others are not having issues with android 13 and droid vnc then assigned to duplicate of #11 is fine...but I highly doubt that rom creator sees merit in running this fringe case down - although I know that you don't have bandwidth, or knowledge of his rom implementation either...is there anythink about the api that he would have to know about to possibly get him knowledge of the interaction he'd have to add to get up and running?

**Comment by bk138** [comment] 2022-10-11 19:09
No idea, as I'm not familiar with those ROMs 🤷 - closing then as dupe of #11 (which kinda goes along the lines "ROM is missing APIs"...

**Closed by bk138** 2022-10-11 19:09 UTC
Labels: bug, answer-needed
