### ISSUE TITLE
Streaming of single app: restrict input to that app

### ISSUE THREAD

**Issue by stegl83** [bk138/droidVNC-NG#196] opened 2024-03-27 21:46 UTC
Streaming of single app correctly restrict the submission of the UI to the app. When you leave the app by interacting directly with the device  - on the device something strange happens.
When clicked on screen (which is still showing the UI of the streamed app) - the click hits the location on the device (which is already moved away from the streamed app).
So you blindly trigger action on device. 

**To Reproduce**
Start VNCServer and stream single app. Connect with RealVNCViewer (portable version 7.10.0)
Leave the app on the device by clicking Home or something else.
Click in VNCViewer on the screen. 

**Expected Behavior**
Blank screen when streamed app is not in foreground on device. Block all input.

Versions:
 - droidVNC-NG version: current
 - Android version: 14 (Pixel 7a)
 - VNC client and version: RealVNCViewer (portable version 7.10.0)

**Comment by bk138** [comment] 2024-03-28 08:47
We don't have fully-fledged support of single-app capturing. You're referring to the new Android 14 feature?

**Comment by bk138** [comment] 2024-04-02 07:27
@stegl83 I just tried with an Android 14 emulator and it always streams the whole screen, as intended - how did you get to access app-specific screen capturing?

**Comment by bk138** [comment] 2024-04-08 18:46
Tentatively closing, please post here and re-open if there are news.

**Closed by bk138** 2024-04-08 18:46 UTC
Labels: feature-request, answer-needed
