### ISSUE TITLE
Port it to magisk module / using root access

### ISSUE THREAD

**Issue by lexavey** [bk138/droidVNC-NG#214] opened 2024-06-12 05:31 UTC
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Is your feature request related to a problem? Please describe.**

Battery drain if always run this app. 
With root access, can you make it using root access to run vnc server daemon
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Your environment (please complete the following information):**
 - droidVNC-NG version:
 - Android version:
 - Client-side OS and version:
 - VNC client and version:

**Comment by bk138** [comment] 2024-06-12 07:49
That's a dupe of #31, please subscribe there.

**Closed by bk138** 2024-06-12 07:49 UTC
