### ISSUE TITLE
Wiki or FAQ: how to wake up from screensaver?

### ISSUE THREAD

**Issue by inspector71** [bk138/droidVNC-NG#42] opened 2021-10-10 04:14 UTC
Great app. Thank you for producing the 1st ever open source remote access app that seems to be easy to install and has substantial potential.

Could I contribute to a Wiki or documentation effort to add some documentation for the basics, at least?

On first run, was not immediately obvious to me that `Esc` (back?) would wake up the screensaver ... without sending through an unwanted keypress whilst doing so :)

Maybe a Wiki and / or FAQ page may help?

**Comment by bk138** [comment] 2022-04-16 16:20
dupe of #37, let's tackle the challenge there

**Closed by bk138** 2022-04-16 16:20 UTC
Labels: documentation

**Comment by sudomain** [comment] 2022-06-29 16:24
My method for waking the device (software ESC didn't work for me) is to ssh into the device and send a notification. I keep Termux's `sshd` running and use Termux:API's `termux-notification` to wake it. Thought I'd just post it here incase a wiki page is made.
