### ISSUE TITLE
no pointer input on a rooted LineageOS 18.1 on a Raspberry Pi 4

### ISSUE THREAD

**Issue by GralfR** [bk138/droidVNC-NG#11] opened 2021-04-03 13:56 UTC
I tried droidVNC-NG 1.0.2 on a rooted [LineageOS 18.1](https://konstakang.com/devices/rpi4/LineageOS18/) on a Raspberry Pi 4.
Finally a VNC-server that works on the new android 11!

Well "works" in some way: I can connect and get the screen on my Win7 or Win10 with the [realVNC viewer](https://www.realvnc.com/de/connect/download/viewer/). The keyboard shortcuts like Pos1 and ESC are working, but no mouse-input, which is more important on an android device than the home- and back-buttons.
The app on android says all three permissions granted.

Which VNC client do You use?

**Comment by bk138** [comment] 2021-04-03 17:33
It should work with any VNC viewer. I rather suspect a server-side issue. Your Pi 4 with Android 11 might lack the respective input APIs. Do other open source remote control solutions work?

**Comment by GralfR** [comment] 2021-04-04 14:08
I did not find any other open source solutions but I've installed the app on an android phone with generic android 8.1.
On that system the app is working fine including mouse support. The only thing is a very slow screen refresh when switching apps on the phone. But that might be due to a slow network connection (there are a lot of spaming wifi around....).
So, it makes clear sense to me, the lineageOS on the pi is lacking APIs. I will comunicate that to the developer.
Thanks

**Comment by bk138** [comment] 2021-04-04 15:46
OK, closing this then.

**Closed by bk138** 2021-04-04 15:46 UTC

**Comment by xilart** [comment] 2022-09-16 12:10
I have the same problem with rooted Android TV 11 and RealVNC. I can see the screen, and Esc\Home buttons work but no reaction to the mouse. How can this be fixed? Which API should be installed and how. Thanks in advance.

**Comment by bk138** [comment] 2022-09-16 12:46
Maybe asking the lineage os guys is worth a try @xilart , I have no idea for droidvnc-ng's part...😕

**Comment by xilart** [comment] 2022-09-16 12:50
> Maybe asking the lineage os guys is worth a try @xilart , I have no idea for droidvnc-ng's part...😕

I use custom Android TV build for Transpeed X4S box with Amlogic Amlogic S905X4 chipset. It has no connection to LineageOS. Any other recommendations how to fix this problem?

**Comment by xilart** [comment] 2022-09-16 12:51
I guess this problem is not related to a specific OS since it reproduced on Android TV 11 OS as well.
