### ISSUE TITLE
Android 6?

### ISSUE THREAD

**Issue by Si03** [bk138/droidVNC-NG#56] opened 2021-11-29 17:36 UTC
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG
(I'm open to this...)

**Describe the solution you'd like**
Would it be possible to support Android 6? 

**Describe alternatives you've considered**
After a lot of searching, we haven't found anything that works.

**Additional context**
We have industrial Android 6 devices that need basic remote support.
Must be via APK
If building for 6 means we lose a feature then that may be ok.

**Comment by bk138** [comment] 2021-11-29 18:57
Hi! Android 6 would be _kinda_ possible, but you'd basically lose input functionality as it requires Android 7 to be properly implemented. If this is OK for you, I'm open to work on it on contract basis, just email me. 

You might also want to contact the guys at abr solutions who did [alphavnc](https://play.google.com/store/apps/details?id=de.abr.android.avnc) which does include some hacks to make input work on Android earlier than 7.

re #23

**Comment by bk138** [comment] 2022-02-22 07:37
Dupe of #9

**Closed by bk138** 2022-02-22 07:37 UTC
Labels: feature-request
