### ISSUE TITLE
built-in keyboard

### ISSUE THREAD

**Issue by mouhsineelachbi** [bk138/droidVNC-NG#58] opened 2022-01-10 22:04 UTC
The feature I want to talk about here is that this app needs a built-in keyboard so user won't just connect and see what only on the screen of the phone but only interact with the option is giving on Its screen 
for example people can be texting from another device through that phone where the droidVNC is installed.

**Comment by bk138** [comment] 2022-01-11 09:23
I reckon this to be a dupe of #4, please leave a note if this here issue is different. Also please take the time to quickly scan for already existing issues :-).

**Closed by bk138** 2022-01-11 09:23 UTC
Labels: duplicate
